version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_productos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_productos
    ports:
      - "3307:3306"